### ISSUE TITLE
Cannot find module... when using pnpm

### ISSUE THREAD

**Issue by a2k42** [Code-Pop/Real-World-Nuxt-3#3]
The readme suggests that `pnpm` can be used with this project but in part 2 of the course, server-side rendering, once the `RenderMarkdown` component has been added, the app stops working with a 500 error.

Adding an `.npmrc` file with `shamefully-hoist=true` seemed to fix it. 

I was under the impression that if you initialised a new nuxt project using pnpm then this file would be created for you, but the last time I tried it didn't so I don't know if this has changed recently.

Error message:

```bash
 ERROR  Cannot find module './lib/'
Require stack:
- /home/user/Real-World-Nuxt-3/markdown-it

  Require stack:
  - markdown-it
  at Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
  at Module._load (node:internal/modules/cjs/loader:934:27)
  at Module.require (node:internal/modules/cjs/loader:1157:19)
  at require (node:internal/modules/helpers:119:18)
  at markdown-it:4:18
  at ViteNodeRunner.runModule (node_modules/.pnpm/vite-node@1.6.0_@types+node@20.12.11_sass@1.77.0_terser@5.31.0/node_modules/vite-node/dist/client.mjs:362:11)
  at ViteNodeRunner.directRequest (node_modules/.pnpm/vite-node@1.6.0_@types+node@20.12.11_sass@1.77.0_terser@5.31.0/node_modules/vite-node/dist/client.mjs:346:16)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async ViteNodeRunner.cachedRequest (node_modules/.pnpm/vite-node@1.6.0_@types+node@20.12.11_sass@1.77.0_terser@5.31.0/node_modules/vite-node/dist/client.mjs:189:14)
  at async ViteNodeRunner.dependencyRequest (node_modules/.pnpm/vite-node@1.6.0_@types+node@20.12.11_sass@1.77.0_terser@5.31.0/node_modules/vite-node/dist/client.mjs:233:12)
```

**Comment by bitsnaps** [comment]
I'm getting the same error: `Cannot find module './lib/' Require stack`... in nuxt v3.11.2.
The issue seems to be related to (vue-markdown-render)[https://github.com/cloudacy/vue-markdown-render] package, upgrading it didn't make any changes, comment out `<RenderMarkdown />` everywhere and the error gone.
P.S. Node v18.19.0.

**Comment by tutorialcode** [comment]
README has been updated with correct instructions:

# How to run this app

Install the dependencies:

```bash
npm install
```

Start the dev server:

```bash
npm run dev
```

Start the mock API server:

```bash
npm run mock-api
```

**Comment by bitsnaps** [comment]
@tutorialcode The mock api was running, this didn't solve the issue.

**Comment by tutorialcode** [comment]
> @tutorialcode The mock api was running, this didn't solve the issue.

You have to first "reset" the project in terms of the package-lock and node_modules folder. Basically revert the package-lock file to exactly how it was originally, and removing node_modules. Then run the npm install command to install everything again.

Alternatively, you can also clone the repo again to a new folder and start from there.
